// Exports mapped objects of icons for use in stories

import {
  IconUIArrowDown,
  IconUIArrowLeft,
  IconUIArrowRight,
  IconUIArrowUp,
  IconUICheckMark,
  IconUIErase,
  IconUIExclamationMark,
  IconUIEyeClosed,
  IconUIEyeOpen,
  IconUIInformation,
  IconUIYouseelogo,
  IconUIMultiplication,
  IconUIPlus,
  IconAddToPlaylist,
  IconAdditionalPackages,
  IconAirplay,
  IconAlbum,
  IconArchive,
  IconArrowLeft,
  IconArrowRight,
  IconArtistRadio,
  IconArtist,
  IconBack10seconds,
  IconBackLeft,
  IconBackToLive,
  IconBill,
  IconBluetooth,
  IconBroadband,
  IconBrowse,
  IconCalendar,
  IconCamera,
  IconCampaigns,
  IconChannels,
  IconCheckmark,
  IconChildren,
  IconChromecast,
  IconClose,
  IconConnectionFail,
  IconConsumption,
  IconContact,
  IconCouple,
  IconData,
  IconDeleteLocked,
  IconDelete,
  IconDownload,
  IconDrag,
  IconEdit,
  IconFamily,
  IconFastForward,
  IconFastForward2,
  IconFavoriteChannels,
  IconFavorites,
  IconFilters,
  IconForum,
  IconForward30seconds,
  IconForwardRight,
  IconGaming,
  IconGenre,
  IconHdmi,
  IconHelp,
  IconHitlist,
  IconHome,
  IconHumax,
  IconInfo,
  IconLandline,
  IconLink,
  IconList,
  IconLiveRadio,
  IconLiveTv,
  IconLocation,
  IconLock,
  IconMail,
  IconMaximize,
  IconMinimize,
  IconMixPackage,
  IconMobileBroadband,
  IconMobileRouter2,
  IconMobileRouter,
  IconMobileSubscriptions,
  IconMobile,
  IconMoreOptions,
  IconMostPlayed,
  IconMovies,
  IconMstv,
  IconMusic,
  IconMute,
  IconNews,
  IconNext,
  IconNotifications,
  IconOn,
  IconOperatingStatus,
  IconOrientationLock,
  IconOutageWarning,
  IconParentalLock,
  IconPause,
  IconPause2,
  IconPaymentCard,
  IconPerson,
  IconPersonalHelp,
  IconPictureInPicture,
  IconPinActive,
  IconPinInactive,
  IconPlay,
  IconPlay2,
  IconPlaylist,
  IconPlus,
  IconPower,
  IconPreview,
  IconPrint,
  IconProfile,
  IconRecentPlaylist,
  IconRecentlyAdded,
  IconRecord,
  IconRecord2,
  IconRemove,
  IconRentalLock,
  IconRepeat,
  IconRestartBox,
  IconRewind,
  IconRewind2,
  IconRouter,
  IconScreenSize,
  IconSearch,
  IconSecurity,
  IconSeriesRecords,
  IconSeries,
  IconSettings,
  IconShare,
  IconShuffle,
  IconSimcard,
  IconSmartHome,
  IconSms,
  IconSongRadio,
  IconSongs,
  IconSortChannels,
  IconSorting,
  IconSpeedtest,
  IconStartOver,
  IconStop,
  IconStop2,
  IconStreaming,
  IconSubtitlesDk,
  IconSubtitles,
  IconSupports,
  IconTablet,
  IconTextTv,
  IconTips,
  IconTrailer,
  IconTvFilm,
  IconTvGuide,
  IconTv,
  IconUnlock,
  IconUpdate,
  IconUpload,
  IconVideoGuide,
  IconVoice,
  IconVolume1,
  IconVolume2,
  IconVolume3,
  IconVoucher,
  IconYouseeCloud,
  IconYouseeMore,
} from '..'

export const uiIcons = {
  none: undefined,
  'ui-arrow-down': IconUIArrowDown,
  'ui-arrow-left': IconUIArrowLeft,
  'ui-arrow-right': IconUIArrowRight,
  'ui-arrow-up': IconUIArrowUp,
  'ui-check-mark': IconUICheckMark,
  'ui-erase': IconUIErase,
  'ui-exclamation-mark': IconUIExclamationMark,
  'ui-eye-closed': IconUIEyeClosed,
  'ui-eye-open': IconUIEyeOpen,
  'ui-information': IconUIInformation,
  'ui-youseelogo': IconUIYouseelogo,
  'ui-multiplication': IconUIMultiplication,
  'ui-plus': IconUIPlus,
}

export const setIcons = {
  none: undefined,
  'add-to-playlist': IconAddToPlaylist,
  'additional-packages': IconAdditionalPackages,
  airplay: IconAirplay,
  album: IconAlbum,
  archive: IconArchive,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'artist-radio': IconArtistRadio,
  artist: IconArtist,
  'back-10seconds': IconBack10seconds,
  'back-left': IconBackLeft,
  'back-to-live': IconBackToLive,
  bill: IconBill,
  bluetooth: IconBluetooth,
  broadband: IconBroadband,
  browse: IconBrowse,
  calendar: IconCalendar,
  camera: IconCamera,
  campaigns: IconCampaigns,
  channels: IconChannels,
  checkmark: IconCheckmark,
  children: IconChildren,
  chromecast: IconChromecast,
  close: IconClose,
  'connection-fail': IconConnectionFail,
  consumption: IconConsumption,
  contact: IconContact,
  couple: IconCouple,
  data: IconData,
  'delete-locked': IconDeleteLocked,
  delete: IconDelete,
  download: IconDownload,
  drag: IconDrag,
  edit: IconEdit,
  family: IconFamily,
  'fast-forward': IconFastForward,
  'fast-forward2': IconFastForward2,
  'favorite-channels': IconFavoriteChannels,
  favorites: IconFavorites,
  filters: IconFilters,
  forum: IconForum,
  'forward-30seconds': IconForward30seconds,
  'forward-right': IconForwardRight,
  gaming: IconGaming,
  genre: IconGenre,
  hdmi: IconHdmi,
  help: IconHelp,
  hitlist: IconHitlist,
  home: IconHome,
  humax: IconHumax,
  info: IconInfo,
  landline: IconLandline,
  link: IconLink,
  list: IconList,
  'live-radio': IconLiveRadio,
  'live-tv': IconLiveTv,
  location: IconLocation,
  lock: IconLock,
  mail: IconMail,
  maximize: IconMaximize,
  minimize: IconMinimize,
  'mix-package': IconMixPackage,
  'mobile-broadband': IconMobileBroadband,
  'mobile-router-2': IconMobileRouter2,
  'mobile-router': IconMobileRouter,
  'mobile-subscriptions': IconMobileSubscriptions,
  mobile: IconMobile,
  'more-options': IconMoreOptions,
  'most-played': IconMostPlayed,
  movies: IconMovies,
  mstv: IconMstv,
  music: IconMusic,
  mute: IconMute,
  news: IconNews,
  next: IconNext,
  notifications: IconNotifications,
  on: IconOn,
  'operating-status': IconOperatingStatus,
  'orientation-lock': IconOrientationLock,
  'outage-warning': IconOutageWarning,
  'parental-lock': IconParentalLock,
  pause: IconPause,
  pause2: IconPause2,
  'payment-card': IconPaymentCard,
  person: IconPerson,
  'personal-help': IconPersonalHelp,
  'picture-in-picture': IconPictureInPicture,
  'pin-active': IconPinActive,
  'pin-inactive': IconPinInactive,
  play: IconPlay,
  play2: IconPlay2,
  playlist: IconPlaylist,
  plus: IconPlus,
  power: IconPower,
  preview: IconPreview,
  print: IconPrint,
  profile: IconProfile,
  'recent-playlist': IconRecentPlaylist,
  'recently-added': IconRecentlyAdded,
  record: IconRecord,
  record2: IconRecord2,
  remove: IconRemove,
  'rental-lock': IconRentalLock,
  repeat: IconRepeat,
  'restart-box': IconRestartBox,
  rewind: IconRewind,
  rewind2: IconRewind2,
  router: IconRouter,
  'screen-size': IconScreenSize,
  search: IconSearch,
  security: IconSecurity,
  'series-records': IconSeriesRecords,
  series: IconSeries,
  settings: IconSettings,
  share: IconShare,
  shuffle: IconShuffle,
  simcard: IconSimcard,
  'smart-home': IconSmartHome,
  sms: IconSms,
  'song-radio': IconSongRadio,
  songs: IconSongs,
  'sort-channels': IconSortChannels,
  sorting: IconSorting,
  speedtest: IconSpeedtest,
  'start-over': IconStartOver,
  stop: IconStop,
  stop2: IconStop2,
  streaming: IconStreaming,
  'subtitles-dk': IconSubtitlesDk,
  subtitles: IconSubtitles,
  supports: IconSupports,
  tablet: IconTablet,
  'text-tv': IconTextTv,
  tips: IconTips,
  trailer: IconTrailer,
  'tv-film': IconTvFilm,
  'tv-guide': IconTvGuide,
  tv: IconTv,
  unlock: IconUnlock,
  update: IconUpdate,
  upload: IconUpload,
  'video-guide': IconVideoGuide,
  voice: IconVoice,
  'volume-1': IconVolume1,
  'volume-2': IconVolume2,
  'volume-3': IconVolume3,
  voucher: IconVoucher,
  'yousee-cloud': IconYouseeCloud,
  'yousee-more': IconYouseeMore,
}

export default {
  ...uiIcons,
  ...setIcons,
}
